# Comrude Configuration File

[app]
name = "Comrude"
version = "0.1.0"
default_provider = "openai"

[ui]
theme = "dark"
auto_save_history = true
max_history_items = 1000

[providers.openai]
enabled = true
api_key_env = "OPENAI_API_KEY"
default_model = "gpt-4o-mini"
max_tokens = 4096
timeout_seconds = 30
base_url = "https://api.openai.com/v1"

[providers.anthropic]
enabled = true
api_key_env = "ANTHROPIC_API_KEY"
default_model = "claude-3-5-sonnet-20241022"
max_tokens = 4096
timeout_seconds = 30
base_url = "https://api.anthropic.com"

[providers.ollama]
enabled = true
endpoint = "http://localhost:11434"
default_model = "codellama:7b"
timeout_seconds = 120
auto_pull_models = false

[files]
max_file_size_mb = 10
allowed_extensions = [
    "rs", "py", "js", "ts", "go", "java", "cpp", "c",
    "md", "txt", "json", "yaml", "toml", "html", "css"
]

[memory]
max_context_turns = 3
max_context_tokens = 8000
enable_diff_compression = true
enable_summarization = true
session_storage_path = ".comrude/sessions"
session_max_age_days = 30